version: 5.1.0

variant: default

navbar:
  menu:
    home: "/"
    news: "/news/"
    honors: "/honors/"
    achievements: "/achievements/"
    members: "/members/"
    alumni: "/alumni/"
    conferences: "/conferences/"
    service: "/service/"
    media: "/media/"
    open_positions: "/open-positions/"
    contact: "/contact/"
  links: {}
